### ISSUE TITLE
Please include the tests directory in your sdist tarball

### ISSUE THREAD

**Issue by rhertzog** [zorro3/ConfigArgParse#11]
I am packaging the module for Kali Linux (needed for a new version of mitmproxy) and I noticed that trying to run the test suite fails because the "tests" directory is missing from the tarball sent to PyPi:
https://pypi.python.org/packages/source/C/ConfigArgParse/ConfigArgParse-0.9.3.tar.gz

You might also want to create proper tags in your Git repository so that one can find out the precise commit used for each release sent to PyPi (and so that we can download tarballs from GitHub as a work-around when the PyPi tarball doesn't suit our needs, like is the case right now).

Thank you!

**Comment by zorro3** [comment]
Thanks for the suggestions!  
I will add tags starting with 0.9.4

Ps.  Let me know if e54bebb doesn't resolve the tests issue.

**Comment by rhertzog** [comment]
Looking good:
```
$ tar tf dist/ConfigArgParse-0.9.3.tar.gz|grep tests
ConfigArgParse-0.9.3/tests/
ConfigArgParse-0.9.3/tests/__init__.py
ConfigArgParse-0.9.3/tests/test_configargparse.py
```

**Comment by yarikoptic** [comment]
so could 0.9.3.1 or better 0.9.4 be cut/pushed?  ;) considering building backports of @rhertzog's packages for neurodebian but would feel much better if we could run tests at package build time.
